<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/11/13
 * Time: 14:58
 */

namespace app\api\controller;

use app\api\logic\ChargeLogic;
use think\Controller;
use think\Request;

class FreeMode extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取签名
     * @param $app_secret
     * @return string
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 9:20
     */
    public static function signature($app_secret)
    {
        $array = [
            time(),     // 时间戳
            'jdx',      // 随机字符串
            $app_secret // app_secret
        ];
        sort($array, SORT_STRING);
        $str = implode($array);
        return md5($str);
    }

    /**
     * 获取二维码
     * @param $ip
     * @param $auth_open_id
     * @param $nickname
     * @param $sex
     * @return mixed
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 11:17
     */
    public static function getQrcode($ip, $auth_open_id, $nickname, $sex)
    {
        $config     = config('FSWS');// 获取配置参数
        $appid      = $config['APPID'];
        $app_secret = $config['APP_SECRET'];
        $url        = $config['URL'];
        $key        = $config['KEY'];
        $signature  = self::signature($app_secret);
        $data       = [
            'key'           => $key,
            'develop_appid' => $appid,
            'timestamp'     => time(),
            'nonce'         => 'jdx',
            'signature'     => $signature,
            'auth_open_id'  => $auth_open_id,
            'nickname'      => $nickname,
            'sex'           => $sex,
            'ip'            => $ip,
        ];
        $res        = httpRequest($url, 'POST', $data);
        return $res;
    }


    /**
     * 创建免费订单
     * @param Request $request
     * @return array
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 14:55
     */
    public function CreateOrder(Request $request)
    {
        $ip                   = $request->ip();
        $param                = $request->param();
        $code                 = $param['code'];
        $number               = $param['number'];
        $index                = $param['index'];
        $urlObj["appid"]      = config('appid');
        $urlObj["secret"]     = config('secret');
        $urlObj["code"]       = $code;
        $urlObj["grant_type"] = "authorization_code";
        $bizString            = $this->ToUrlParams($urlObj);
        $url                  = "https://api.weixin.qq.com/sns/oauth2/access_token?" . $bizString;
        $data                 = httpRequest($url, 'POST');// 获取网页授权access_token和用户openid
        $data                 = json_decode($data, true);
        $user_info_url        = "https://api.weixin.qq.com/sns/userinfo?access_token={$data['access_token']}&openid={$data['openid']}&lang=zh_CN";
        $user_info            = httpRequest($user_info_url, 'GET');// 获取微信用户信息
        $user_info            = json_decode($user_info, true);// 获取微信用户信息
        if ($user_info['errcode']) { // 获取用户信息失败，返回错误信息
            // 或者重新进入获取免费二维码流程
            $url = "http://{$_SERVER['HTTP_HOST']}/index.php/api/FreeMode/getCodeUrl?number={$number}&index={$index}";
            Header("Location: $url");
            exit();
        } else {
            $openid   = $user_info['openid'];
            $nickname = $user_info['nickname'];
            $sex      = $user_info['sex'];
            $head_pic = $user_info['headimgurl'];
            // 获取二维码前首先检查用户，是否已经有免费的订单了，有的话，直接查询历史订单，直接过期掉
            $order_res = M("power_order_free")->where(['openid' => $openid])->order('id', 'desc')->find();
            // 用户还未使用该密码，可以更新设备密码
            if ($order_res['pay_status'] == 1) {
                // 如果订单还在可使用状态下，那么可以继续获取密码
                $order_res['pay_status'] = 3; // 过期处理
                M("power_order_free")->update($order_res);
            }
            $QrCode = self::getQrcode($ip, $openid, $nickname, $sex); // 获取微信二维码
            $QrCode = json_decode($QrCode, true);
            if ($QrCode['code'] === 20000) {
                // 获取二维码成功，给用户下免费订单
                // 创建唯一订单号
                $order_sn = 'QR' . date('Ymd') . substr(implode(NULL, array_map('ord', str_split(substr(uniqid(), 7, 13), 1))), 0, 8) . rand(10000, 99000);
                // 如果订单还在可使用状态下，那么可以继续获取密码
                $password  = self::create_password($number);
                $order     = [ // 收集订单信息
                    'order_sn'    => $order_sn,
                    'openid'      => $openid,
                    'nickname'    => $nickname,
                    'head_pic'    => $head_pic,
                    'ip'          => $ip,
                    'appid'       => $QrCode['data']['appid'],
                    'appname'     => $QrCode['data']['appname'],
                    'qrcode_url'  => $QrCode['data']['qrcode_url'],
                    'code'        => $QrCode['data']['code'],
                    'number'      => $number,
                    'price'       => $QrCode['data']['bidding'] / 100,
                    'pay_price'   => $QrCode['data']['bidding'] / 100,
                    'time'        => 60, // 单位为分钟
                    'key'         => 4,
                    'password'    => $password,
                    'create_time' => time(),
                    'pay_status'  => 1,
                ];
                $order_res = M("power_order_free")->add($order);
                if ($order_res) {
                    // 创建成功，跳转前端显示视图，前端获取二维码信息
                    self::RedirectFreeQrCode($openid, $number);
                } else {
                    die("网络错误！！");
                }
            } else {
                // 没有请求到二维码，获取二维码失败，直接给用户返回密码
                // 没有免费的资源了，直接跳转到显示密码页面，并且携带上密码参数
                $password = self::create_password($number);
                $url      = "http://{$_SERVER['HTTP_HOST']}/index.php/api/FreeMode/getOrderInfo?password=$password";
                Header("location:" . $url);
                die;
            }
        }
    }

    /**
     * 转换链接地址参数
     * @param $urlObj
     * @return string
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/15 14:50
     */
    public function ToUrlParams($urlObj)
    {
        $buff = "";
        foreach ($urlObj as $k => $v) {
            if ($k != "sign") {
                $buff .= $k . "=" . $v . "&";
            }
        }
        $buff = trim($buff, "&");
        return $buff;
    }


    /**
     * 中间跳转获取CODE，需要用到code换取用户的信息，来创建订单
     * @param Request $request
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 13:52
     */
    public function getCodeUrl(Request $request)
    {
        $number                  = $request->get('number');
        $index                   = $request->get('index');
        $redirectUrl             = "http://{$_SERVER['HTTP_HOST']}/index.php/api/FreeMode/CreateOrder?number={$number}&index={$index}"; // 请求第三方公众号二维码，创建免费订单地址
        $urlObj["appid"]         = config('APPID');
        $urlObj["redirect_uri"]  = "$redirectUrl";
        $urlObj["response_type"] = "code";
        $urlObj["scope"]         = "snsapi_userinfo";
        $urlObj["state"]         = "STATE" . "#wechat_redirect";
        $bizString               = $this->ToUrlParams($urlObj);
        $url                     = "https://open.weixin.qq.com/connect/oauth2/authorize?" . $bizString;
        Header("Location: $url"); // 跳转到微信授权页面 需要用户确认登录的页面
        exit();
    }

    /**
     * 跳转到免费关注二维码页面
     * @param $openid
     * @param $number
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 17:21
     */
    public static function RedirectFreeQrCode($openid, $number)
    {
        $url = "http://{$_SERVER['HTTP_HOST']}/dist/index.html#/free_qr_code?openid={$openid}&number={$number}";
        Header("location:" . $url);
        die;
    }


    /**
     * 免费模式获取免费二维码订单中的二维码
     * @param Request $request
     * @return array|\think\response\Json
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 17:47
     */
    public function getFreeQrCode(Request $request)
    {
        $openid = $request->post('openid');
        $number = $request->post('number');
        if (empty($openid)) {
            return returnBad("请传入openid", 500);
        }
        if (empty($number)) {
            return returnBad("请传入设备编号", 500);
        }
        $where = ['openid' => $openid, 'number' => $number];
        $order = M('power_order_free')->where($where)->order('id', 'desc')->find();
        if ($order) {
            return returnOk(['qrcode_url' => $order['qrcode_url'], 'code' => $order['code']]);
        } else {
            // 打印日志到文件
            IszmxwLog('where.txt', json_encode($where));
            IszmxwLog('order.txt', json_encode($order));
            return returnBad("网络错误，请您重新扫描设备", 500);
        }
    }


    /**
     * 获取充电订单信息
     * @param Request $request
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/12/13 15:34
     */
    public function getOrderInfo(Request $request)
    {
        $password = $request->get('password');
        if ($password) {
            $redirectUrl = "http://{$_SERVER['HTTP_HOST']}/index.php/api/FreeMode/getPassword?password=$password";
        } else {
            $redirectUrl = "http://{$_SERVER['HTTP_HOST']}/index.php/api/FreeMode/getPassword";
        }
        $urlObj["appid"]         = config('APPID');
        $urlObj["redirect_uri"]  = "$redirectUrl";
        $urlObj["response_type"] = "code";
        $urlObj["scope"]         = "snsapi_userinfo";
        $urlObj["state"]         = "STATE" . "#wechat_redirect";
        $bizString               = $this->ToUrlParams($urlObj);
        $url                     = "https://open.weixin.qq.com/connect/oauth2/authorize?" . $bizString;
        Header("Location: $url"); // 跳转到微信授权页面 需要用户确认登录的页面
        exit();
    }

    /**
     * 获取充电密码
     * @param Request $request
     * @return array
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 18:02
     */
    public function getPassword(Request $request)
    {
        // 获取code
        $code                 = $request->get('code');
        $password             = $request->get('password');
        $urlObj["appid"]      = config('appid');
        $urlObj["secret"]     = config('secret');
        $urlObj["code"]       = $code;
        $urlObj["grant_type"] = "authorization_code";
        $bizString            = $this->ToUrlParams($urlObj);
        $url                  = "https://api.weixin.qq.com/sns/oauth2/access_token?" . $bizString;
        $data                 = httpRequest($url, 'POST');// 获取网页授权access_token和用户openid
        $data                 = json_decode($data, true);
        $openid               = $data['openid'];
        if ($password) {
            $password_url = "http://{$_SERVER['HTTP_HOST']}/dist/index.html#/free_password?openid={$openid}&password=$password";
        } else {
            $password_url = "http://{$_SERVER['HTTP_HOST']}/dist/index.html#/free_password?openid={$openid}";
        }
        Header("Location: $password_url"); // 跳转到微信授权页面 需要用户确认登录的页面
        exit();
    }


    /**
     * 获取密码
     * @param Request $request
     * @return \think\response\View
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/14 18:16
     */
    public function password(Request $request)
    {
        try {
            $param  = $request->param();
            $openid = $param['openid'];
            if ($openid) {
                $order = M("power_order_free")->where(['openid' => $openid])->order('id', 'desc')->find();
                if (is_null($order['pay_time'])) {
                    $data['pay_status'] = 2;
                    $data['pay_time']   = time();
                    $re                 = M("power_order_free")->where(['id' => $order['id']])->update($data);
                    if ($re) {
                        // 处理分润
                        self::Divided($order);
                    }
                }
                return json(['code' => 200, 'msg' => '密码获取成功', 'data' => ['number' => $order['password']]]);
            } else {
                return json(['code' => 500, 'msg' => '获取密码失败，请传入openid']);
            }
        } catch (\Exception $e) {
            IszmxwLog('ii.txt', json_encode($e));
        }
    }

    /**
     * 服务器回调地址
     * @param Request $request
     * @return string
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/18 10:32
     * 回调地址文档：https://note.youdao.com/ynoteshare1/index.html?id=7baaa118ee964b88a1b6d3ab1f0b450b&type=note#消息推送
     */
    public function callback_fsws(Request $request)
    {
        $param  = $request->param();
        $appid  = $param['appid'];
        $openid = $param['auth_open_id'];
        file_put_contents('i.txt', json_encode($param));
        if (empty($appid)) {
            return returnBad('no appid', 500);
        }
        if (empty($auth_open_id)) {
            return returnBad('no openid', 500);
        }
        // 判断这条订单是否已经更改过状态
        $order    = M("power_order")->where(['appid' => $appid, 'openid' => $openid])->find();
        $order_sn = $order['order_sn'];
        if (empty($order['pay_status'])) {
            return returnBad('no order', 500);
        }
        // 做一些订单相关的操作
    }


    /**
     * 分润函数,该分润方法转自原有的分润方法
     * 控制器目录位置application->api->controller->Weixin.php
     * 函数位置   power_notify（）方法里面
     * 大约410行位置开始
     * 这里修改了添加日志的方法，修改了sd_shou_log表的字段，
     * 添加了openid字段，代替原有的pay_user_id字段的含义，但原有的pay_user_id字段还是并存的
     * 添加了order_type字段，为了区别订单的类型，order_type=1为免费模式订单，0为默认的订单类型
     * @param $order
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/11/18 16:49
     */
    public static function Divided($order)
    {
        /*******************************************分润处理开始*********************************************************/
        // 酒店分润处理查找分润
        // 查找设备绑定的酒店和分销商
        $order_sn = $order['order_sn'];
        $money    = $order['pay_price']; // 订单金额
        $number   = $order['number'];    // 设备编号
        // 通过openid查找支付人的user_id，可能为null，因为还未注册
        $pay_user_id         = M("users")->where(['openid' => $order['openid']])->value('user_id');
        $lc_equipment_number = M("lc_equipment_number")->where(['number' => $order['number']])->field("j_user_id,f_user_id")->find();
        // 查找酒店的分润比例
        // 这里进行替换，因为是免费的模式，所以免费模式查询设备免费的相关分润百分比
//        $hotel     = M('lc_apply')->where(['user_id' => $lc_equipment_number['j_user_id']])->value("one_level");
        $hotel = M('lc_apply')->where(['user_id' => $lc_equipment_number['j_user_id']])->value("one_level_free");
        // 公共可分润比例
        $subcommission = M("lc_subcommission")->where(['id' => 1])->value("agent_free");
        $subcommission = intval($subcommission);
        $hotel         = intval($hotel);
        if ($hotel > 0) {
            $hotel_bl = number_format($hotel / 100, 2);//酒店可得分润比例
            $j_money  = number_format($money * $hotel_bl, 2);//酒店可获得分润金额
            if ($j_money > 0) {
                M("users")->where(['user_id' => $lc_equipment_number['j_user_id']])->setInc('user_money', $j_money);//往酒店人员零钱添加分润金额
                // 添加分润记录
                // 未注册的用户可能没有pay_user_id，一般免单的新用户都是没有的
                $array = ['user_id' => $lc_equipment_number['j_user_id'], 'money' => $money, 'allf_money' => $j_money, 'pay_user_id' => $pay_user_id, 'order_type' => 1, 'openid' => $order['openid'], 'time' => time(), 'type' => 1, 'order_sn' => $order_sn, 'subcommission' => $hotel, 'number' => $number];
                M("shou_log")->add($array);
            }
        }

        // 分销商比例分成
        // 1.查找身份
        $f_level            = M("users")->where(['user_id' => $lc_equipment_number['f_user_id']])->field('level')->find();
        $f_level['agent_f'] = M("lc_apply")->where(['user_id' => $lc_equipment_number['f_user_id']])->value("one_level_free");
        if ($f_level['level'] == 5) {// 是总代理
            // 2,查看是否用的是公共分润比例
            $f_bili = intval($f_level['agent_f']);
            if ($f_bili > 0) {// 是,得到最终比例（总-酒店=代理）
                $result_bili = $f_bili - $hotel;
            } else {// 否
                $result_bili = $subcommission - $hotel;
            }
            if ($result_bili > 0) {
                $total_bl = number_format($result_bili / 100, 2);//总代理可得分润比例
                $z_money  = number_format($money * $total_bl, 2);//总代理可获得分润金额
                if ($z_money > 0) {
                    M("users")->where(['user_id' => $lc_equipment_number['f_user_id']])->setInc('user_money', $z_money);//往总代理零钱添加分润金额
                    // 添加分润记录(收入记录)
                    $array = ['user_id' => $lc_equipment_number['f_user_id'], 'money' => $money, 'allf_money' => $z_money, 'pay_user_id' => $pay_user_id, 'order_type' => 1, 'openid' => $order['openid'], 'time' => time(), 'type' => 3, 'order_sn' => $order_sn, 'subcommission' => $result_bili, 'number' => $number];
                    M("shou_log")->add($array);
                }
            }
        } else {// 不是总代理身份
            // 查找分销商分成比例
            $f_fcbili = M('lc_apply')->where(['user_id' => $lc_equipment_number['f_user_id']])->value("one_level_free");
            // 可分成 = 自己所有-分配给酒店
            $f_fcbilis = intval($f_fcbili) - $hotel;
            if ($f_fcbilis > 0) {
                $f_fcbiliv = number_format($f_fcbilis / 100, 2);//分销商可得分润比例
                $f_money   = number_format($money * $f_fcbiliv, 2);//分销商可获得分润金额
                if ($f_money > 0) {
                    M("users")->where(['user_id' => $lc_equipment_number['f_user_id']])->setInc('user_money', $f_money);//往分代人员零钱添加分润金额
                    //添加分润记录
                    //添加分润记录(收入记录)
                    $array = ['user_id' => $lc_equipment_number['f_user_id'], 'money' => $money, 'allf_money' => $f_money, 'pay_user_id' => $pay_user_id, 'order_type' => 1, 'openid' => $order['openid'], 'time' => time(), 'type' => 2, 'order_sn' => $order_sn, 'subcommission' => $f_fcbilis, 'number' => $number];
                    M("shou_log")->add($array);
                }
            }

            // 查找上级总代理
            $entry_uid = M('lc_apply')->where(['user_id' => $lc_equipment_number['f_user_id']])->value("entry_uid");
            if ($entry_uid) {
                $one_level          = M("lc_apply")->where(['user_id' => $entry_uid])->value('one_level_free');
                $f_level['agent_f'] = $one_level;
                $f_bili             = intval($f_level['agent_f']);
                if ($f_bili > 0) {//是,得到最终比例（总-分销商=自己）
                    $result_bili = $f_bili - $f_fcbili;
                } else {//否
                    $result_bili = $subcommission - $f_fcbili;
                }

                if ($result_bili > 0) {
                    $total_bl = number_format($result_bili / 100, 2);//总代理可得分润比例
                    $z_money  = number_format($money * $total_bl, 2);//总代理可获得分润金额
                    if ($z_money > 0) {
                        M("users")->where(['user_id' => $entry_uid])->setInc('user_money', $z_money);//往总代理零钱添加分润金额
                        //添加分润记录(收入记录)
                        $array = ['user_id' => $entry_uid, 'money' => $money, 'allf_money' => $z_money, 'pay_user_id' => $pay_user_id, 'order_type' => 1, 'openid' => $order['openid'], 'time' => time(), 'type' => 3, 'order_sn' => $order_sn, 'subcommission' => $result_bili, 'number' => $number];
                        M("shou_log")->add($array);
                    }
                }
            }
        }
        /*******************************************分润处理结束*********************************************************/
    }

    public function iszmxw()
    {
        $key                    = $_GET['key'];
        $number                 = $_GET['number'];
        $charge_param['key']    = $key;     // TODO 设置密码第一位,四为免费模式的半小时,但是系统中老的旧板子，传输4可能密码无效, 添加上限此功能的时间为2019-11-21 17:11:00:00
        $charge_param['number'] = $number;  // 设置密码第一位JDX19A007984
        $chargeLogic            = new ChargeLogic();
        $password               = $chargeLogic->getChargeCode($charge_param);
        echo $password;
    }


    /**
     * 生成密码
     * @param $number
     * @return string
     * @author: iszmxw <mail@54zm.com>
     * @Date：2019/12/13 15:45
     */
    public static function create_password($number)
    {
        // 如果订单还在可使用状态下，那么可以继续获取密码
        $charge_param['key']    = 4;        // TODO 设置密码第一位,四为免费模式的半小时,但是系统中老的旧板子，传输4可能密码无效, 添加上限此功能的时间为2019-11-21 17:11:00:00
        $charge_param['number'] = $number;  // 设置密码第一位
        $chargeLogic            = new ChargeLogic();
        $password               = $chargeLogic->getChargeCode($charge_param);
        return $password;
    }
}

