<?phphttps://admin.he01.cn/20190906gyjqrcode.jpg
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/20
 * Time: 10:57
 */

namespace app\api\controller;

use app\api\controller\Weixin;

use app\api\service\Token;

use think\Controller;

class Login extends Controller {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index($code = ''){

        $weixin = new Weixin();
        $openid = I('openid','');

        if($openid){

            $userinfo = M('users')->where((['openid'=>$openid]))->find();
            
            if(!$userinfo)
            {
                echo json_encode(['code'=>301,'msg'=>'会员信息不存在']);
            }
            echo json_encode(['code'=>301,'msg'=>'获取成功','openid'=>$openid]);

        }else{

            echo json_encode(['code'=>301,'msg'=>'请求openid失败']);
        }

    }

    //获取小程序openid
    public function getopenid(){
        $code=input('code');
        //头像昵称
        $infodata['nickname']=input('nickname');
        $infodata['head_pic']=input('head_pic');
        $weixin = new \app\api\controller\Weixin();
        $openid=$weixin->get_openid($code);
        if($openid){
            $userinfo = M('users')->where((['openid'=>$openid]))->find();
            
            if($userinfo){
                //更新头像和昵称
                if (!empty($infodata['nickname'])&&!empty($infodata['head_pic'])){
                    M('users')->where(['openid'=>$openid])->save($infodata);
                }

              echo  returnApiSuccess(['msg'=>'获取openid数据成功','openid'=>$openid,'user_id'=>$userinfo['user_id']]);

            }else{

                $user_id = Users::addUser($openid);
                M('users')->where(['user_id'=>$user_id])->save($infodata);
                $info = Db::name('users')->where('openid',$openid)->find();
               echo returnApiSuccess(['msg'=>'保存openid数据成功','openid'=>$info['openid'],'user_id'=>$info['user_id']]);

            }

        }else{
           echo json_encode(array('msg'=>'获取openID失败','code'=>1000));
        }
    }

}

